language: python
python:
  - "2.7"
  - "3.5"
services:
  - postgresql
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: DJANGO_SETTINGS_MODULE=d4s2.settings_test python manage.py test
before_script:
  - psql -c 'create database d4s2;' -U postgres
