version: '3'
services:
  db:
    image: postgres
    env_file: d4s2.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    env_file: d4s2.env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
