version: '2'
services:
  web:
    build: ./production
    image: quay.io/dukegcb/d4s2-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './certdata:/etc/external/'
    # docker-compose doesn't allow specifying the entrypoint while preserving the
    # Dockerfile's command. Since the base docker-compose file specifies an entrypoint
    # we must provide the command here.
    command: supervisord -c /etc/supervisord.conf -n
