version: '2'
services:
  db:
    image: postgres
    env_file: handoverservice.env
  web:
    build: .
    image: dukegcb/handoverservice
    env_file: handoverservice.env
    ports:
      - "8000:8000"
    depends_on:
      - db
