# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('client_id', models.CharField(max_length=64)),
                ('client_secret', models.CharField(max_length=64)),
                ('authorization_uri', models.URLField()),
                ('token_uri', models.URLField()),
                ('redirect_uri', models.URLField()),
                ('scope', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
