# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_auth', '0002_oauthservice_resource_uri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthState',
        ),
    ]
