# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_auth', '0003_oauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='token_json',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='oauthtoken',
            unique_together=set([('user', 'service')]),
        ),
    ]
