# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_auth', '0005_auto_20161118_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
