# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_auth', '0006_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthservice',
            name='revoke_uri',
            field=models.URLField(default='https://oauth.oit.duke.edu/oidc/revoke'),
            preserve_default=False,
        ),
    ]
