# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_auth', '0008_dukedsapitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukedsapitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
