# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_auth', '0009_auto_20161205_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='DukeDSSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('portal_root', models.URLField()),
                ('openid_provider_id', models.CharField(max_length=64)),
            ],
        ),
    ]
