version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: d4s2
          POSTGRES_HOST_AUTH_METHOD=trust
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: |
            source venv/bin/activate
            DJANGO_SETTINGS_MODULE=d4s2.settings_test python manage.py test
