# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0002_remove_dukedsuser_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='token',
            field=models.TextField(db_index=True),
        ),
    ]
