# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0003_auto_20161201_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='token',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='token',
        ),
        migrations.AddField(
            model_name='delivery',
            name='transfer_id',
            field=models.CharField(default='', max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='transfer_id',
            field=models.CharField(db_index=True, default='transfer_id', max_length=36),
            preserve_default=False,
        ),
    ]
