# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0004_auto_20161202_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='user_message',
            field=models.TextField(help_text='Custom message to include about this item when sending notifications', null=True),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='user_message',
            field=models.TextField(help_text='Custom message to include about this item when sending notifications', null=True),
        ),
        migrations.AddField(
            model_name='historicalshare',
            name='user_message',
            field=models.TextField(help_text='Custom message to include about this item when sending notifications', null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='user_message',
            field=models.TextField(help_text='Custom message to include about this item when sending notifications', null=True),
        ),
    ]
