# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-26 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0006_auto_20170330_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='to_users',
            field=models.ManyToManyField(related_name='deliveries_to_users', to='d4s2_api.DukeDSUser'),
        ),
        migrations.AddField(
            model_name='share',
            name='to_users',
            field=models.ManyToManyField(related_name='shares_to_users', to='d4s2_api.DukeDSUser'),
        ),
    ]
