# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0006_auto_20170330_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='share_to_users',
            field=models.ManyToManyField(blank=True, related_name='deliveries_shared_to', to='d4s2_api.DukeDSUser'),
        ),
    ]
