# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-26 18:30
from __future__ import unicode_literals

from django.db import migrations


def populate_share_deliver_to_users(apps, schema_editor):
    models = [
        apps.get_model('d4s2_api', 'Share'),
        apps.get_model('d4s2_api', 'Delivery'),
    ]
    for model in models:
        for item in model.objects.all():
            item.to_users = [item.to_user]
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0007_auto_20171026_1820'),
    ]

    operations = [
        migrations.RunPython(populate_share_deliver_to_users),
    ]
