# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0007_delivery_share_to_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryShareUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dds_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='from_user_new',
            field=models.CharField(help_text='DukeDS uuid user sending delivery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='project_new',
            field=models.CharField(help_text='DukeDS uuid project to deliver', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='to_user_new',
            field=models.CharField(help_text='DukeDS uuid user receiving delivery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='from_user_new',
            field=models.CharField(help_text='DukeDS uuid user sending delivery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='project_new',
            field=models.CharField(help_text='DukeDS uuid project to deliver', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='to_user_new',
            field=models.CharField(help_text='DukeDS uuid user receiving delivery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalshare',
            name='from_user_new',
            field=models.CharField(help_text='DukeDS uuid user sharing the project', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalshare',
            name='project_new',
            field=models.CharField(help_text='DukeDS uuid project to share with', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalshare',
            name='to_user_new',
            field=models.CharField(help_text='DukeDS uuid user having project shared with them', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='from_user_new',
            field=models.CharField(help_text='DukeDS uuid user sharing the project', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='project_new',
            field=models.CharField(help_text='DukeDS uuid project to share with', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='to_user_new',
            field=models.CharField(help_text='DukeDS uuid user having project shared with them', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryshareuser',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_to_users', to='d4s2_api.Delivery'),
        ),
    ]
