# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-26 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0008_copy_deliver_share_to_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='historicalshare',
            name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='share',
            name='to_user',
        ),
    ]
