# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-19 21:21
from __future__ import unicode_literals

from django.db import migrations


def copy_delivery_dds_ids_to_new_locations(apps, schema_editor):
    Delivery = apps.get_model('d4s2_api', 'Delivery')
    DeliveryShareUser = apps.get_model('d4s2_api', 'DeliveryShareUser')
    for row in Delivery.objects.all():
        row.project_new = row.project.project_id
        row.from_user_new = row.from_user.dds_id
        row.to_user_new = row.to_user.dds_id
        row.save()
        for share_to_user in row.share_to_users.all():
            DeliveryShareUser.objects.create(delivery=row, dds_id=share_to_user.dds_id)


def copy_share_dds_ids_to_new_locations(apps, schema_editor):
    Share = apps.get_model('d4s2_api', 'Share')
    for row in Share.objects.all():
        row.project_new = row.project.project_id
        row.from_user_new = row.from_user.dds_id
        row.to_user_new = row.to_user.dds_id
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0008_new_share_delivery_dds_fields'),
    ]

    operations = [
        migrations.RunPython(copy_delivery_dds_ids_to_new_locations, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(copy_share_dds_ids_to_new_locations, reverse_code=migrations.RunPython.noop),
    ]
