# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-19 21:21
from __future__ import unicode_literals

from django.db import migrations

HISTORY_TABLES_NULL_TO_BLANK_SQL = [
    'UPDATE "d4s2_api_historicaldelivery" SET "project_id" = \'\' WHERE "project_id" IS NULL',
    'UPDATE "d4s2_api_historicaldelivery" SET "from_user_id" = \'\' WHERE "from_user_id" IS NULL',
    'UPDATE "d4s2_api_historicaldelivery" SET "to_user_id" = \'\' WHERE "to_user_id" IS NULL',
    'UPDATE "d4s2_api_historicalshare" SET "project_id" = \'\' WHERE "project_id" IS NULL',
    'UPDATE "d4s2_api_historicalshare" SET "from_user_id" = \'\' WHERE "from_user_id" IS NULL',
    'UPDATE "d4s2_api_historicalshare" SET "to_user_id" = \'\' WHERE "to_user_id" IS NULL'
]

class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0012_remove_dukeds_project'),
    ]

    operations = [
        migrations.RunSQL(sql=HISTORY_TABLES_NULL_TO_BLANK_SQL, reverse_sql=migrations.RunSQL.noop),
    ]
