# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0013_0_null_to_blank_history_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='from_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user sending delivery', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='project_id',
            field=models.CharField(default='', help_text='DukeDS uuid project to deliver', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='to_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user receiving delivery', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='from_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user sending delivery', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='project_id',
            field=models.CharField(default='', help_text='DukeDS uuid project to deliver', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='to_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user receiving delivery', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalshare',
            name='from_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user sharing the project', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalshare',
            name='project_id',
            field=models.CharField(default='', help_text='DukeDS uuid project to share with', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalshare',
            name='to_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user having project shared with them', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='share',
            name='from_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user sharing the project', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='share',
            name='project_id',
            field=models.CharField(default='', help_text='DukeDS uuid project to share with', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='share',
            name='to_user_id',
            field=models.CharField(default='', help_text='DukeDS uuid user having project shared with them', max_length=255),
            preserve_default=False,
        ),
    ]
