# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0013_1_dds_id_fields_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryshareuser',
            name='dds_id',
            field=models.CharField(max_length=36),
        ),
    ]
