# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-23 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('d4s2_api', '0014_auto_20180130_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailTemplateSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='d4s2_api.EmailTemplateSet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='d4s2_api.EmailTemplateSet'),
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.EmailTemplateSet'),
        ),
    ]
