# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0016_email_group_to_set'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set([('template_set', 'template_type')]),
        ),
        migrations.RemoveField(
            model_name='historicalemailtemplate',
            name='group',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d4s2_api.EmailTemplateSet'),
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='group',
        ),

    ]
