# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-06 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0017_auto_20180323_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dukedsuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='DukeDSUser',
        ),
    ]
