# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-12 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('d4s2_api', '0018_auto_20180406_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalS3Delivery',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined')], default=0)),
                ('decline_reason', models.TextField(blank=True)),
                ('performed_by', models.TextField(blank=True)),
                ('delivery_email_text', models.TextField(blank=True)),
                ('completion_email_text', models.TextField(blank=True)),
                ('user_message', models.TextField(blank=True, help_text='Custom message to include about this item when sending notifications', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical s3 delivery',
            },
        ),
        migrations.CreateModel(
            name='S3Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of S3 bucket', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='S3Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined')], default=0)),
                ('decline_reason', models.TextField(blank=True)),
                ('performed_by', models.TextField(blank=True)),
                ('delivery_email_text', models.TextField(blank=True)),
                ('completion_email_text', models.TextField(blank=True)),
                ('user_message', models.TextField(blank=True, help_text='Custom message to include about this item when sending notifications', null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='d4s2_api.S3Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='S3Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='URL of S3 service', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='S3User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_id', models.CharField(help_text='S3 user ID (aws_access_key_id)', max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Agent')], default=0)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d4s2_api.S3Endpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='S3UserCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_secret_access_key', models.CharField(help_text='S3 user ID (aws_access_key_id)', max_length=255)),
                ('s3_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='d4s2_api.S3User')),
            ],
        ),
        migrations.AddField(
            model_name='s3delivery',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_deliveries', to='d4s2_api.S3User'),
        ),
        migrations.AddField(
            model_name='s3delivery',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_deliveries', to='d4s2_api.S3User'),
        ),
        migrations.AddField(
            model_name='s3bucket',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d4s2_api.S3Endpoint'),
        ),
        migrations.AddField(
            model_name='s3bucket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_buckets', to='d4s2_api.S3User'),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='bucket',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.S3Bucket'),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='from_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.S3User'),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='to_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.S3User'),
        ),
        migrations.AlterUniqueTogether(
            name='s3delivery',
            unique_together=set([('bucket', 'from_user', 'to_user')]),
        ),
    ]
