# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-16 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0020_auto_20180412_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='DDSDelivery',
        ),
        migrations.RenameModel(
            old_name='DeliveryShareUser',
            new_name='DDSDeliveryShareUser',
        ),
        migrations.RenameModel(
            old_name='HistoricalDelivery',
            new_name='HistoricalDDSDelivery',
        ),
        migrations.AlterModelOptions(
            name='historicalddsdelivery',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dds delivery'},
        ),
    ]
