# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0022_auto_20180417_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3endpoint',
            name='name',
            field=models.CharField(default='default', help_text='Unique name of the s3 service', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
