# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0023_s3endpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicals3delivery',
            name='transfer_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='s3delivery',
            name='transfer_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
