# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-30 15:49
from __future__ import unicode_literals

from django.db import migrations


def replace_text_in_template(apps, schema_editor, find_text=None, replace_text=None):
    EmailTemplate = apps.get_model('d4s2_api', 'EmailTemplate')
    for template in EmailTemplate.objects.all():
        template.body = template.body.replace(find_text, replace_text)
        template.subject = template.subject.replace(find_text, replace_text)
        template.save()


def replace_dds_text_with_service_name_var(apps, schema_editor):
    # Changes instance of 'Duke Data Service' in email templates to '{{ service_name }}'
    replace_text_in_template(apps, schema_editor, find_text='Duke Data Service', replace_text='{{ service_name }}')


def replace_service_name_var_with_dds_text(apps, schema_editor):
    # Changes instance of '{{ service_name }}' in email templates to 'Duke Data Service'
    replace_text_in_template(apps, schema_editor, find_text='{{ service_name }}', replace_text='Duke Data Service')




class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0024_auto_20180423_2026'),
    ]

    operations = [
        migrations.RunPython(replace_dds_text_with_service_name_var, reverse_code=replace_service_name_var_with_dds_text)
    ]
