# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0024_auto_20180423_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDSDeliveryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='S3DeliveryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ddsdelivery',
            name='completion_email_text',
        ),
        migrations.RemoveField(
            model_name='historicalddsdelivery',
            name='completion_email_text',
        ),
        migrations.RemoveField(
            model_name='historicals3delivery',
            name='completion_email_text',
        ),
        migrations.RemoveField(
            model_name='s3delivery',
            name='completion_email_text',
        ),
        migrations.AddField(
            model_name='ddsdelivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ddsdelivery',
            name='sender_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalddsdelivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalddsdelivery',
            name='sender_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='sender_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='s3delivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='s3delivery',
            name='sender_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ddsdelivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (5, 'Transferring')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalddsdelivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (5, 'Transferring')], default=0),
        ),
        migrations.AlterField(
            model_name='historicals3delivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (5, 'Transferring')], default=0),
        ),
        migrations.AlterField(
            model_name='s3delivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (5, 'Transferring')], default=0),
        ),
        migrations.AddField(
            model_name='s3deliveryerror',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='d4s2_api.S3Delivery'),
        ),
        migrations.AddField(
            model_name='ddsdeliveryerror',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='d4s2_api.DDSDelivery'),
        ),
    ]
