# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0025_auto_20180502_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsdelivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalddsdelivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='s3delivery',
            name='recipient_completion_email_text',
            field=models.TextField(blank=True),
        ),
    ]
