# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-30 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0025_auto_20180430_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddsdeliveryerror',
            old_name='user_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='s3deliveryerror',
            old_name='user_message',
            new_name='message',
        ),
    ]
