# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-03 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0026_auto_20180502_1457'),
        ('d4s2_api', '0025_auto_20180430_1549'),
    ]

    operations = [
    ]
