# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0027_auto_20180502_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddsdeliveryerror',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='s3deliveryerror',
            name='message',
            field=models.TextField(),
        ),
    ]
