# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-07 14:43
from __future__ import unicode_literals

from django.db import migrations

ACCEPTED_RECIPIENT_TYPE = 'accepted_recipient'


def load_email_template_types(apps, schema_editor):
    EmailTemplateType = apps.get_model("d4s2_api", "EmailTemplateType")
    EmailTemplateType.objects.create(name=ACCEPTED_RECIPIENT_TYPE)


def unload_email_template_types(apps, schema_editor):
    EmailTemplateType = apps.get_model("d4s2_api", "EmailTemplateType")
    for email_template_type in EmailTemplateType.objects.filter(name=ACCEPTED_RECIPIENT_TYPE):
        email_template_type.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0028_auto_20180507_1441'),
    ]

    operations = [
        migrations.RunPython(load_email_template_types, reverse_code=unload_email_template_types),
    ]
