# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-11 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0029_new_email_template_types'),
        ('d4s2_api', '0029_auto_20180510_1930'),
    ]

    operations = [
    ]
