# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0030_auto_20180514_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddsdelivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (4, 'Failed'), (5, 'Transferring'), (6, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalddsdelivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (4, 'Failed'), (5, 'Transferring'), (6, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='historicals3delivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (4, 'Failed'), (5, 'Transferring'), (6, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='s3delivery',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined'), (4, 'Failed'), (5, 'Transferring'), (6, 'Canceled')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ddsdelivery',
            unique_together=set([]),
        ),
    ]
