# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-24 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0032_delivery_canceled_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsdelivery',
            name='email_template_set',
            field=models.ForeignKey(help_text='Email template set to be used with this delivery', null=True, on_delete=django.db.models.deletion.CASCADE, to='d4s2_api.EmailTemplateSet'),
        ),
        migrations.AddField(
            model_name='historicalddsdelivery',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.EmailTemplateSet'),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.EmailTemplateSet'),
        ),
        migrations.AddField(
            model_name='s3delivery',
            name='email_template_set',
            field=models.ForeignKey(help_text='Email template set to be used with this delivery', null=True, on_delete=django.db.models.deletion.CASCADE, to='d4s2_api.EmailTemplateSet'),
        ),
    ]
