# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0034_auto_20180925_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalddsdelivery',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicals3delivery',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalshare',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
