# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-27 15:00
from __future__ import unicode_literals

from django.db import migrations


def fill_email_template_set_based_on_creating_user(apps, schema_editor):
    fill_email_template_set_based_on_creating_user_for_model(apps, 'DDSDelivery')
    fill_email_template_set_based_on_creating_user_for_model(apps, 'S3Delivery')
    fill_email_template_set_based_on_creating_user_for_model(apps, 'Share')


def fill_email_template_set_based_on_creating_user_for_model(apps, model_name):
    model_class = apps.get_model('d4s2_api', model_name)
    history_model_class = apps.get_model('d4s2_api', 'Historical' + model_name)
    UserEmailTemplateSet = apps.get_model('d4s2_api', 'UserEmailTemplateSet')
    for row in model_class.objects.all():
        history_row = history_model_class.objects.get(history_type='+', id=row.id)
        user_email_template_set = UserEmailTemplateSet.objects.get(user=history_row.history_user)
        print(row, user_email_template_set)
        row.email_template_set = user_email_template_set.email_template_set
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0034_auto_20180925_2042'),
    ]

    operations = [
        migrations.RunPython(fill_email_template_set_based_on_creating_user, reverse_code=migrations.RunPython.noop),
    ]
