# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0035_auto_20181226_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplateset',
            name='cc_address',
            field=models.EmailField(blank=True, help_text='Optional address to CC when using this template set', max_length=254),
        ),
        migrations.AddField(
            model_name='emailtemplateset',
            name='reply_address',
            field=models.EmailField(blank=True, help_text="Optional address to set as reply-to when using this template set (replacing the sending user's email address", max_length=254),
        ),
    ]
