# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0037_auto_20190306_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsdelivery',
            name='project_name',
            field=models.TextField(blank=True, default='', help_text='Copy of the project name from when delivery is accepted.'),
        ),
        migrations.AddField(
            model_name='historicalddsdelivery',
            name='project_name',
            field=models.TextField(blank=True, default='', help_text='Copy of the project name from when delivery is accepted.'),
        ),
    ]
