# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0038_auto_20200327_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatetype',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailtemplatetype',
            name='sequence',
            field=models.IntegerField(help_text='determines order', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='d4s2_api.EmailTemplateSet'),
        ),
    ]
