# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0039_auto_20200615_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplateset',
            name='group_name',
            field=models.CharField(blank=True, help_text='Name of the group manager group users must belong to to use this group.', max_length=64),
        ),
    ]
