# Generated by Django 3.2.6 on 2021-08-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0040_emailtemplateset_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalddsdelivery',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Email template set to be used with this delivery', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.emailtemplateset'),
        ),
        migrations.AlterField(
            model_name='historicals3delivery',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Email template set to be used with this delivery', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.emailtemplateset'),
        ),
        migrations.AlterField(
            model_name='historicalshare',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Email template set to be used with this share', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.emailtemplateset'),
        ),
    ]
