# Generated by Django 3.2.6 on 2021-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0041_auto_20210827_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3objectmanifest',
            name='content',
            field=models.JSONField(help_text='JSON array of object metadata from bucket at time of sending bucket'),
        ),
    ]
