# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0041_auto_20220310_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplateset',
            name='storage',
            field=models.CharField(choices=[('dds', 'Duke Data Service'), ('azure', 'Azure Blob Storage')], default='dds', max_length=64),
        ),
    ]
