# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-23 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('d4s2_api', '0042_emailtemplateset_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailtemplateset',
            name='storage',
            field=models.CharField(choices=[('dds', 'Duke Data Service'), ('azure', 'Azure Blob Storage')], default='dds', max_length=64),
        ),
        migrations.AlterField(
            model_name='useremailtemplateset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useremailtemplateset',
            unique_together=set([('user', 'storage')]),
        ),
    ]
