# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0043_auto_20220323_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplateset',
            name='storage',
            field=models.CharField(choices=[('dds', 'Duke Data Service'), ('azure', 'Azure Blob Storage'), ('s3', 'S3')], default='dds', max_length=64),
        ),
        migrations.AlterField(
            model_name='useremailtemplateset',
            name='storage',
            field=models.CharField(choices=[('dds', 'Duke Data Service'), ('azure', 'Azure Blob Storage'), ('s3', 'S3')], default='dds', max_length=64),
        ),
    ]
