# Generated by Django 3.2.11 on 2022-04-26 12:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0043_auto_20220323_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azdelivery',
            name='share_user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='emailtemplateset',
            name='storage',
            field=models.CharField(choices=[('dds', 'Duke Data Service'), ('azure', 'Azure Blob Storage'), ('s3', 'S3')], default='dds', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalazdelivery',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Email template set to be used with this delivery', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.emailtemplateset'),
        ),
        migrations.AlterField(
            model_name='historicalazdelivery',
            name='share_user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='historicalddsdelivery',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Email template set to be used with this delivery', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.emailtemplateset'),
        ),
        migrations.AlterField(
            model_name='historicals3delivery',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Email template set to be used with this delivery', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.emailtemplateset'),
        ),
        migrations.AlterField(
            model_name='historicalshare',
            name='email_template_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Email template set to be used with this share', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='d4s2_api.emailtemplateset'),
        ),
        migrations.AlterField(
            model_name='s3objectmanifest',
            name='content',
            field=models.JSONField(help_text='JSON array of object metadata from bucket at time of sending bucket'),
        ),
        migrations.AlterField(
            model_name='useremailtemplateset',
            name='storage',
            field=models.CharField(choices=[('dds', 'Duke Data Service'), ('azure', 'Azure Blob Storage'), ('s3', 'S3')], default='dds', max_length=64),
        ),
    ]
