# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0044_auto_20220608_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='azdelivery',
            name='fund_code',
            field=models.CharField(blank=True, help_text='Fund code used to bill storage costs.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalazdelivery',
            name='fund_code',
            field=models.CharField(blank=True, help_text='Fund code used to bill storage costs.', max_length=255),
        ),
    ]
