# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4s2_api', '0045_auto_20220613_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='azdelivery',
            name='transfer_uuid',
            field=models.UUIDField(help_text='UUID field used with transfer webhook.', null=True),
        ),
        migrations.AddField(
            model_name='historicalazdelivery',
            name='transfer_uuid',
            field=models.UUIDField(help_text='UUID field used with transfer webhook.', null=True),
        ),
    ]
