"""
Django settings for d4s2 project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from d4s2.settings_base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h0$3*q5f-(bjusx_93*$&%ihg9e48^49(vp&jn2-fc2k#ip*+r'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd4s2',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# To enable SMTP email, uncomment EMAIL_BACKEND and supply an SMTP host
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = ''
USERNAME_EMAIL_HOST = ""
