# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (4, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='handover',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
    ]
