# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='state',
            field=models.IntegerField(choices=[(1, 'Notified')], default=1),
        ),
        migrations.AlterField(
            model_name='handover',
            name='state',
            field=models.IntegerField(choices=[(0, 'Initiated'), (1, 'Notified'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='dds_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together=set([('project_id', 'from_user_id', 'to_user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='handover',
            unique_together=set([('project_id', 'from_user_id', 'to_user_id')]),
        ),
    ]
