# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0002_auto_20160405_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DukeDSUser',
        ),
    ]
