# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handover_api', '0003_auto_20160406_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukedsuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
