# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0004_dukedsuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
