# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0005_handover_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukedsuser',
            name='api_key',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
