# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0006_auto_20160412_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
