# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0008_historicaldraft_historicalhandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='performed_by',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalhandover',
            name='performed_by',
            field=models.TextField(blank=True),
        ),
    ]
