# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0009_auto_20160428_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='handover_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaldraft',
            name='email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalhandover',
            name='completion_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalhandover',
            name='handover_email_text',
            field=models.TextField(blank=True),
        ),
    ]
