# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0010_auto_20160527_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='DukeDSProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=36, unique=True)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dukedsuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dukedsuser',
            name='full_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dukedsuser',
            name='api_key',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
