# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Prior to this migration, user and project UUIDs were stored in the model
# and details were looked up on demand. This migration updates Handovers
# and Drafts to refer to projects and users in a separate model (table)
# so the below custom migrations are used to populate these tables sparsely
# with IDs that already existed

def link_users_and_projects(apps, schema_editor, model):
    DukeDSUser = apps.get_model('handover_api', 'DukeDSUser')
    DukeDSProject = apps.get_model('handover_api', 'DukeDSProject')
    db_alias = schema_editor.connection.alias
    for m in model.objects.using(db_alias).all():
        from_user, _ = DukeDSUser.objects.get_or_create(dds_id=m.from_user_id)
        to_user, _ = DukeDSUser.objects.get_or_create(dds_id=m.to_user_id)
        project, _ = DukeDSProject.objects.get_or_create(project_id=m.project_id)
        m.from_ds_user = from_user
        m.to_ds_user = to_user
        m.ds_project = project
        m.save()


def link_draft_users(apps, schema_editor):
    Draft = apps.get_model('handover_api', 'Draft')
    link_users_and_projects(apps, schema_editor, Draft)


def link_handover_users(apps, schema_editor):
    Handover = apps.get_model('handover_api', 'Handover')
    link_users_and_projects(apps, schema_editor, Handover)


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0011_auto_20160614_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldraft',
            name='from_user_id',
        ),
        migrations.RemoveField(
            model_name='historicaldraft',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='historicaldraft',
            name='to_user_id',
        ),
        migrations.RemoveField(
            model_name='historicalhandover',
            name='from_user_id',
        ),
        migrations.RemoveField(
            model_name='historicalhandover',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='historicalhandover',
            name='to_user_id',
        ),
        migrations.AddField(
            model_name='draft',
            name='ds_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='handover_api.DukeDSProject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='from_ds_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts_from', to='handover_api.DukeDSUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='to_ds_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts_to', to='handover_api.DukeDSUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handover',
            name='ds_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='handover_api.DukeDSProject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handover',
            name='from_ds_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handovers_from', to='handover_api.DukeDSUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handover',
            name='to_ds_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handovers_to', to='handover_api.DukeDSUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldraft',
            name='ds_project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='handover_api.DukeDSProject'),
        ),
        migrations.AddField(
            model_name='historicaldraft',
            name='from_ds_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='handover_api.DukeDSUser'),
        ),
        migrations.AddField(
            model_name='historicaldraft',
            name='to_ds_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='handover_api.DukeDSUser'),
        ),
        migrations.AddField(
            model_name='historicalhandover',
            name='ds_project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='handover_api.DukeDSProject'),
        ),
        migrations.AddField(
            model_name='historicalhandover',
            name='from_ds_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='handover_api.DukeDSUser'),
        ),
        migrations.AddField(
            model_name='historicalhandover',
            name='to_ds_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='handover_api.DukeDSUser'),
        ),
        migrations.RunPython(link_draft_users),
        migrations.RunPython(link_handover_users),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together=set([('ds_project', 'from_ds_user', 'to_ds_user')]),
        ),
        migrations.RemoveField(
            model_name='draft',
            name='from_user_id',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='to_user_id',
        ),
        migrations.AlterUniqueTogether(
            name='handover',
            unique_together=set([('ds_project', 'from_ds_user', 'to_ds_user')]),
        ),
        migrations.RemoveField(
            model_name='handover',
            name='from_user_id',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='to_user_id',
        ),
        # Finally, remove nullability
        migrations.AlterField(model_name='draft',name='ds_project',
                              field=models.ForeignKey(default=None, null=False,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='drafts_from', to='handover_api.DukeDSUser'),
                              ),
        migrations.AlterField(model_name='draft', name='from_ds_user',
                              field=models.ForeignKey(default=None, null=False,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='drafts_from', to='handover_api.DukeDSUser'),
                              ),
        migrations.AlterField(model_name='draft', name='to_ds_user',
                              field=models.ForeignKey(default=None, null=False,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='drafts_to', to='handover_api.DukeDSUser'),
                              ),
        migrations.AlterField(model_name='handover', name='ds_project',
                              field=models.ForeignKey(default=None, null=False,
                                                      on_delete=django.db.models.deletion.CASCADE, to='handover_api.DukeDSProject'),
                              ),
        migrations.AlterField(model_name='handover', name='from_ds_user',
                              field=models.ForeignKey(default=None, null=False,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='handovers_from', to='handover_api.DukeDSUser'),
                              ),
        migrations.AlterField(model_name='handover', name='to_ds_user',
                              field=models.ForeignKey(default=None, null=False,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='handovers_to', to='handover_api.DukeDSUser'),
                              ),
    ]
