# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0012_auto_20160614_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='from_ds_user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='ds_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='to_ds_user',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='from_ds_user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='ds_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='to_ds_user',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='historicaldraft',
            old_name='from_ds_user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='historicaldraft',
            old_name='ds_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='historicaldraft',
            old_name='to_ds_user',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='historicalhandover',
            old_name='from_ds_user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='historicalhandover',
            old_name='ds_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='historicalhandover',
            old_name='to_ds_user',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together=set([('project', 'from_user', 'to_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='handover',
            unique_together=set([('project', 'from_user', 'to_user')]),
        ),
    ]
