# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0013_auto_20160614_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts_from', to='handover_api.DukeDSUser'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handover_api.DukeDSProject'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts_to', to='handover_api.DukeDSUser'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_from', to='handover_api.DukeDSUser'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handover_api.DukeDSProject'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_to', to='handover_api.DukeDSUser'),
        ),
    ]
