# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0014_auto_20160616_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDraft',
            new_name='HistoricalShare',
        ),
        migrations.RenameModel(
            old_name='Draft',
            new_name='Share',
        ),
        migrations.AlterModelOptions(
            name='historicalshare',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical share'},
        ),
    ]
