# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0016_auto_20160919_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshare',
            name='role',
            field=models.TextField(default='file_downloader'),
        ),
        migrations.AddField(
            model_name='share',
            name='role',
            field=models.TextField(default='file_downloader'),
        ),
    ]
