# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0017_auto_20160920_1758'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set([('project', 'from_user', 'to_user', 'role')]),
        ),
    ]
