# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

TEMPLATE_TYPES = (
    'share_file_downloader',
    'share_project_viewer',
    'share_file_editor',
    'share_file_uploader',
    'share_project_admin',
    'delivery',
    'accepted',
    'declined',
)


def load_email_template_types(apps, schema_editor):
    EmailTemplateType = apps.get_model("handover_api", "EmailTemplateType")
    for template_type in TEMPLATE_TYPES:
        EmailTemplateType.objects.create(name=template_type)


def unload_email_template_types(apps, schema_editor):
    EmailTemplateType = apps.get_model("handover_api", "EmailTemplateType")
    EmailTemplateType.objects.delete(name__in=TEMPLATE_TYPES)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handover_api', '0018_auto_20160920_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmailTemplate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='handover_api.EmailTemplateType')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical email template',
            },
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handover_api.EmailTemplateType'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set([('group', 'template_type')]),
        ),
        migrations.RunPython(load_email_template_types, reverse_code=unload_email_template_types)
    ]
