# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0019_auto_20160922_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatetype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
