# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0020_auto_20160922_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handover',
            old_name='reject_reason',
            new_name='decline_reason',
        ),
        migrations.RenameField(
            model_name='historicalhandover',
            old_name='reject_reason',
            new_name='decline_reason',
        ),
        migrations.AlterField(
            model_name='handover',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalhandover',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Notified'), (2, 'Accepted'), (3, 'Declined')], default=0),
        ),
    ]
