# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0021_auto_20160922_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='historicalemailtemplate',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='subject',
            field=models.TextField(default='{{ subject }}'),
            preserve_default=False,
        ),
    ]
