# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-23 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0022_auto_20160922_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Handover',
            new_name='Delivery',
        ),
        migrations.RenameModel(
            old_name='HistoricalHandover',
            new_name='HistoricalDelivery',
        ),
        migrations.AlterModelOptions(
            name='historicaldelivery',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical delivery'},
        ),
    ]
