# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0023_auto_20160923_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_from', to='handover_api.DukeDSUser'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_to', to='handover_api.DukeDSUser'),
        ),
    ]
