# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-23 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover_api', '0024_auto_20160923_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='handover_email_text',
            new_name='delivery_email_text',
        ),
        migrations.RenameField(
            model_name='historicaldelivery',
            old_name='handover_email_text',
            new_name='delivery_email_text',
        ),
    ]
